project_id = "pkngmgdspvttmddvtask"

[functions.google-translate]
verify_jwt = true

[functions.openai-chat]
verify_jwt = true

[functions.bhashini-translate]
verify_jwt = true

[functions.google-speech]
verify_jwt = true

[functions.razorpay-subscription]
verify_jwt = true

[functions.razorpay-webhook]
verify_jwt = false

[functions.msg91-otp]
verify_jwt = false