project_id = "pkngmgdspvttmddvtask"

[functions.google-translate]
verify_jwt = true

[functions.openai-chat]
verify_jwt = true

[functions.azure-speech]
verify_jwt = true

[functions.bhashini-translate]
verify_jwt = true

[functions.google-speech]
verify_jwt = true