// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkngmgdspvttmddvtask.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrbmdtZ2RzcHZ0dG1kZHZ0YXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzAyNTIsImV4cCI6MjA3MjQwNjI1Mn0.jPSRb_zXId1SfL4TGQVlCjr2dEMAKxfNpfRKP6Py-pE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});